#!/usr/bin/env python3
"""Derive a retirement/legacy input.json from a base (refinance-oriented) one.

The base input is built for a short, nominal-dollar refinance comparison. A
retirement question needs a different framing, so this recasts it as an overlay
on the base rather than a hand-built config (DP#18: overlays modify, they don't
replace):

  - REAL dollars: a real return, 0% real salary growth and frozen brackets, so
    balances, the spending target and the estate tax are all in today's money.
  - A dated horizon: ``assumptions.horizon_age`` (DP#1) instead of a magic year
    count; the engine derives the span from the primary's birth_year.
  - Opening registered balances moved onto the members, where they belong —
    RRSP/TFSA are per-person accounts (DP#4).
  - The readvanceable/HELOC leverage and the education savings are excluded:
    both are separate decisions that otherwise swamp the retirement signal.

Personal figures live only in the (gitignored) input files this reads and writes;
nothing personal is hardcoded here (DP#15).

Usage:
    uv run python make_retirement_input.py [BASE_INPUT] [OUT_INPUT]
"""
import json
import sys

DEFAULT_BASE = "inputs/active/input.json"
DEFAULT_OUT = "inputs/active/input-retirement.json"

HORIZON_AGE = 95          # plan until the primary turns 95
REAL_RETURN = 0.05        # nominal return less long-run inflation
NET_SPENDING_TARGET = 125_000   # today's-dollar NET household spending
BASELINE_RETIREMENT_AGE = 60    # the analyzer sweeps candidate_ages


def build(base: dict) -> dict:
    d = json.loads(json.dumps(base))  # deep copy (DP#18: overlay a base)

    d['$comment'] = (
        "RETIREMENT/LEGACY overlay on input.json, generated by "
        "make_retirement_input.py. REAL (today's) dollars: real return, 0% real "
        "salary growth, frozen brackets. Horizon is dated via "
        "assumptions.horizon_age (DP#1). Consumed by retirement_analysis.py to "
        "sweep retirement age x drawdown strategy and quantify longevity + "
        "after-tax legacy. Refinance scenarios do not apply here."
    )

    a = d['assumptions']
    # DP#1: the horizon is a rule ("plan until the primary turns N"); the engine
    # derives projection_years from birth_year + start_year. No magic count.
    a['horizon_age'] = HORIZON_AGE
    a.pop('projection_years', None)
    a['investment_return'] = REAL_RETURN
    a['salary_growth'] = 0.0
    a['frozen_brackets'] = True
    # Issue #597 / #585: the recast to real dollars used to be recorded ONLY in
    # this comment. Declare it in the config itself so every output surface
    # (model_fidelity.describe_units, consumed by output_plugins.py) can state
    # nominal-vs-real instead of leaving the reader to infer it.
    a['dollar_basis'] = 'real'
    a['base_year'] = a.get('start_year')

    d.setdefault('return_model', {})['rate'] = REAL_RETURN
    d['return_model']['rates_for_sensitivity'] = [0.03, REAL_RETURN, 0.07]

    # Exclude the readvanceable/Smith-Manoeuvre leverage: over a multi-decade
    # horizon the undrawn margin is otherwise carried as debt that compounds
    # unserviced and swamps the retirement signal. It is a separate decision.
    d['property']['heloc_readvance'] = False
    d['property']['margin_available'] = 0
    for k in ('balance', 'personal_portion', 'investment_portion'):
        d.setdefault('heloc', {})[k] = 0.0

    members = d['family']['members']
    for m in members:
        m['retirement_age'] = BASELINE_RETIREMENT_AGE

    # Opening registered balances belong on the member — RRSP/TFSA are per-person
    # accounts (DP#4). The base input carries them only as household totals under
    # portfolio.accounts.*; keep them there for composition/yield, and attribute
    # the balances to the owner recorded in the scenario's SITUATION notes.
    primary = next(m for m in members if m['role'] == 'primary')
    spouse = next((m for m in members if m['role'] == 'spouse'), None)
    accounts = d.get('portfolio', {}).get('accounts', {})
    primary['rrsp_balance'] = accounts.get('rrsp', {}).get('balance', 0)
    primary['tfsa_balance'] = 0
    if spouse:
        spouse['rrsp_balance'] = 0
        spouse['tfsa_balance'] = accounts.get('tfsa', {}).get('balance', 0)

    ret = d.setdefault('retirement', {})
    ret['spending_target'] = NET_SPENDING_TARGET
    ret['candidate_ages'] = [55, 58, 60, 62, 65]
    ret['rrif_conversion_age'] = 71
    # Locked-in (LIF/LIRA) must be in the order or it never funds spending.
    ret['drawdown_order'] = ['tfsa', 'non_reg', 'rrsp', 'lif', 'lira']

    # Education savings are earmarked for the children and are drawn down as EAPs
    # within a few years — not retirement capital. Left in, they compound for
    # decades and overstate the estate.
    d.setdefault('accounts', {})['resp_current_balance'] = 0.0

    return d


def main():
    base_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_BASE
    out_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    with open(base_path) as f:
        base = json.load(f)
    with open(out_path, 'w') as f:
        json.dump(build(base), f, indent=2)
    print("wrote", out_path)


if __name__ == '__main__':
    main()
